### ISSUE TITLE
Sections appear missing but are seen at lower page widths

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#59]
Screengrab/videos (insert file names here)
2019 08 20, Sections appear missing but are seen at lower page widths.mp4
[2019 08 20, Sections appear missing but are seen at lower page widths.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3521426/2019.08.20.Sections.appear.missing.but.are.seen.at.lower.page.widths.mp4.zip)
2019 08 20, Web inspector video for bug about elements not appearing at certain widths
[2019 08 20, Web inspector video for bug about elements not appearing at certain widths.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3521427/2019.08.20.Web.inspector.video.for.bug.about.elements.not.appearing.at.certain.widths.mp4.zip)

Link and Node #
Dupral 8 Link:
•	http://bostond8stg.prod.acquia-sites.com/node/4286

Dupral 7 Link:
•	https://boston.gov/node/4286

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > MacOS 10.14.6 > Safari 12.1.2

Section
(Page > Area > Element)
Profile Page > Page elements > Page width

Brief Description
Page elements appear missing but are actually seen on the page at different page widths. I have looked at the Safari Web Inspector to verify that the sections are on the page, but are invisible

Steps to reproduce
1. Open a Dupral 7 and Dupral 8 page for node 4286
2. Check out the differences between the elements (Note: Address may be missing from the Event section on the Dupral 8 page)
3. Make the Dupral 8 page less wide until more sections appear in the Event section

Desired Result
•	All the elements are visible at all widths of the page

Actual Result
•	Not all elements are visible on all widths of the page

**Comment by ollie-iterators** [comment]
This is connected to issue #58

**Comment by jimafisk** [comment]
Here are all the differences I notice when I do a one-to-one comparison on `/node/4286`:

<details>
<summary>D8 intro text is missing the squiggle line</summary>

D7:

![d7_squiggle](https://user-images.githubusercontent.com/5913244/63973151-2bb9e480-ca78-11e9-9b16-515e8d30de6b.png)

D8:

![d8_squiggle](https://user-images.githubusercontent.com/5913244/63973161-31172f00-ca78-11e9-81b9-a715aa5ead91.png)

</details>
<details>
<summary>The spacing is too large between drawers in D8</summary>

D7:

![d7_drawers](https://user-images.githubusercontent.com/5913244/63973411-b4388500-ca78-11e9-915e-232197dad255.png)

D8:

![d8_drawers](https://user-images.githubusercontent.com/5913244/63973416-b7cc0c00-ca78-11e9-9338-b74a195e38aa.png)

</details>
<details>
<summary>The events_and_notices component is missing completely</summary>

D7:

![d7_upcoming_events](https://user-images.githubusercontent.com/5913244/63973205-4ee49400-ca78-11e9-9bea-35ace7f074e2.png)

D8:

![d8_upcoming_events](https://user-images.githubusercontent.com/5913244/63973208-5310b180-ca78-11e9-877d-18d133e2e094.png)

</details>
<details>
<summary>The news_and_announcements component is blank in D8</summary>

D7:

![d7_news_and_announcements](https://user-images.githubusercontent.com/5913244/63973254-64f25480-ca78-11e9-88bb-61c2e1287b71.png)

D8:

![d8_news_and_announcements](https://user-images.githubusercontent.com/5913244/63973266-69b70880-ca78-11e9-9741-730309ca667e.png)

</details>
<details>
<summary>In Group of Links - Mini Grid component the title is missing from documents</summary>

D7:

![d7_resource_title](https://user-images.githubusercontent.com/5913244/63973348-99fea700-ca78-11e9-9bd0-1db69bf29529.png)

D8:

![d8_resource_title](https://user-images.githubusercontent.com/5913244/63973356-9f5bf180-ca78-11e9-9a7b-11bd25f0dd54.png)

</details>

**Comment by mmcgowanBOS** [comment]
I believe the missing Address info is now fixed. It's persistent across all page widths as far as I can see. There still may be issues as Jim mentioned above, but am currently not seeing the original issue logged.

**Comment by jimafisk** [comment]
Diagnoses / fixes for issues:
1.  **Squiggle line:** Added preprocess (converted from D7) to add missing classes to `field_intro_text`
2.  **Drawer spacing:** Updated the `field_drawer` display on the Drawers paragraph to remove surrounding `<div>`s which stop `:first-child` pseudo CSS selectors from working
3.  **Missing events_and_notices:** Seems to be the same underlying data migration issue as https://github.com/CityOfBoston/boston.gov-d8/issues/467
4.  **Blank news_and_announcements:** Both the D7 and D8 views are setting "related" as the display for the component, but 2 of the underlying related nodes (`/node/63726` and `/node/60276`) show 403 errors for anonymous users in D8 (related to an issue @davidrkupton is looking into) and the other 2 related nodes (`/node/63251` and `/node/63231`) seem to be available and tagged correctly via `field_related` - looking into this deeper.
5. **Missing title from Group of Links:** Document field is not templated correctly

**Comment by jimafisk** [comment]
Ok I've partially fixed the "related" display for the `news_and_announcements` view, so this should extend to a bunch of these components across the site. Basically the issue was we set a views relationship from the post node to `field_related` and then we use that relationship in a contextual filter using content id from URL. The issue was we were requiring the relationship to `field_featured_post` on the `field_related` relationship which was an error. So now it works for an authenticated user (`/node/63251` and `/node/63231` are showing):

![auth](https://user-images.githubusercontent.com/5913244/64040932-1dc59b80-cb2c-11e9-8634-744571c25357.png)

Need to figure out why it's still blank for anonymous users...

**Comment by jimafisk** [comment]
When testing it seemed that post nodes were not showing up for anonymous users on the upcoming display either. I was able to fix this by removing the filter the looked for `nid` using the `field_featured_post` relationship, which attempts to remove a featured post from the grid. 

The above action did not fix related_posts. In order to do that I had to remove both relationships for featured posts on the related display. 

Currently investigating how to reimplement these features in a non-breaking way.
