### ISSUE TITLE
The button for 2019 leaf and yard waste schedule has no text on the Drupal 8 site

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#92]
Screengrab/videos (insert file names here)
2019 09 13, Button on Drupal 8 site has no text.mp4
[2019 09 13, Button on Drupal 8 site has no text.MP4.zip](https://github.com/CityOfBoston/Iterators/files/3610433/2019.09.13.Button.on.Drupal.8.site.has.no.text.MP4.zip)

Link and Node #
Dupral 8 Link:
•	http://bostond8stg.prod.acquia-sites.com/trash-and-recycling-guide

Dupral 7 Link:
•	https://www.boston.gov/trash-and-recycling-guide

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > Windows 10 (1903) > Chrome 77

Section
(Page > Area > Element)
Trash and Recycling Guide > Quick Links > 2019 leaf and yard waste schedule button

Brief Description
The button for 2019 leaf and yard waste schedule has no text on the Drupal 8 site

Steps to reproduce
1. Go to the Trash and Recycling Guide page for Drupal 7 and Drupal 8
2. Go to the quick links section

Desired Result
•	All the links have text on them

Actual Result
•	The link for 2019 leaf and yard waste schedule has no text on it for the Drupal 8 site

**Comment by mmcgowanBOS** [comment]
I believe this is fixed.

**Comment by ollie-iterators** [comment]
This is not fixed on the Computer nor is it fixed on the iPhone

**Comment by jimafisk** [comment]
Looks fixed:

![link_text](https://user-images.githubusercontent.com/5913244/65458885-a29a9100-de1c-11e9-87f9-31642063a19d.png)

Closing, cc @mmcgowanBOS
