### ISSUE TITLE
The buttons in the Quick Links Section for the Trash and Recycling Guide page on the Drupal 8 pages do not have any icons

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#98]
Screengrab/videos (insert file names here)
2019 09 13, The buttons in the Quick Links section have no icons on the Drupal 8 page.mp4
[2019 09 13, The buttons in the Quick Links section have no icons on the Drupal 8 page.MP4.zip](https://github.com/CityOfBoston/Iterators/files/3610656/2019.09.13.The.buttons.in.the.Quick.Links.section.have.no.icons.on.the.Drupal.8.page.MP4.zip)

Link and Node #
Dupral 8 Link:
•	http://bostond8stg.prod.acquia-sites.com/trash-and-recycling-guide

Dupral 7 Link:
•	https://www.boston.gov/trash-and-recycling-guide

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Phone  > iOS 12.4.1 > Safari

Section
(Page > Area > Element)
Trash and Recycling Guide > Quick Links section > Button Icons

Brief Description
The buttons in the Quick Links Section for the Trash and Recycling Guide page on the Drupal 8 pages do not have any icons

Steps to reproduce
1. Go to the Rash and Recycling Guide page for Drupal 7 and Drupal 8
2. Go to the Quick Links Section 

Desired Result
•	Both pages have the proper content for the section

Actual Result
•	The buttons for the Quick Links section for the Drupal 8 page have no icons

**Comment by mmcgowanBOS** [comment]
It looks like this has been fixed.

**Comment by ollie-iterators** [comment]
This is still happening on the iPhone and the button for Food Access on the bottom of the page also does not have an icon

**Comment by mmcgowanBOS** [comment]
This seems to fixed already on the D8 site.

**Comment by reillyzlab** [comment]
Resolved so closing
